### ISSUE TITLE
Plugin fails with ES-1.4.0.Beta1

### ISSUE THREAD

**Issue by hmalphettes** [Asquera/elasticsearch-http-basic#26]
Build 1.3.2 of the plugin crashes ES-1.4.0.Beta1 with the error:
`1) No implementation for org.elasticsearch.http.HttpServerTransport was bound.`

The RestAction branch build 1.3.2 also breaks with
`1) NoSuchMethodError[org.elasticsearch.rest.BaseRestHandler.<init>(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/client/Client;)V]
make: *** [start] Error 3`

**Comment by ranji** [comment]
since 1.4 is out of beta, any chance that you will have a release version? Thank you.

**Comment by sconno05** [comment]
Would also appreciate a release version here, thanks!

**Comment by emig** [comment]
Published a new version https://github.com/Asquera/elasticsearch-http-basic/releases/tag/v1.4.0
