### ISSUE TITLE
{"OK":{}} breaks kopf

### ISSUE THREAD

**Issue by nekinie** [Asquera/elasticsearch-http-basic#36]
Theres a control panel for ElasticSearch called kopf that we use to manage and monitor parts of our elasticsearch cluster, enabling your plugin removes the normal cluster health info from http://127.0.0.1:9200/ and instead returns {"OK":{}}

Is there anyway to enable your plugin but still see the normal responce info from this endpoint?

**Comment by emig** [comment]
Hi, I just merged this PR that brings the standard health check back: https://github.com/Asquera/elasticsearch-http-basic/pull/35 .
