### ISSUE TITLE
Standard ES info on /

### ISSUE THREAD

**Issue by ineu** [Asquera/elasticsearch-http-basic#38]
With authentication enabled, ES always responds with empty hash on /, whether authenticated or not. This is a bug as there's no way to get standard ES response.
It was discussed in https://github.com/Asquera/elasticsearch-http-basic/issues/18. Are there plans to include the fix to the master?

**Comment by ben-av** [comment]
+1 on this.
Can't work with curator because of it

**Comment by emig** [comment]
Fixed in tag v1.5.0 (version 1.5.0) https://github.com/Asquera/elasticsearch-http-basic/commit/c49d5554a10d89e0d83d53db0ba99ee10e6065f8

**Comment by ineu** [comment]
Awesome, thanks!
