### ISSUE TITLE
Want to enforce authentization for local host

### ISSUE THREAD

**Issue by shruthi-uottawa** [Asquera/elasticsearch-http-basic#41]
Hi,

We are evaluating the use of the plugin to enforce authentication while using the web interface or from the command line using curl commands. But I see that the local host is whitelisted be default in the code and there is no option to remove that config. It would be great if you could add an option to remove local host from the whitelist as that seems to leave a slight gap in addressing the security concern.

Also another thing we observed was when we run 
$ curl -v --user (username):(wrong password) localhost:9200/ 

It sends status 200 OK. Looks like no authentication is happening whereas your guide on testing says that the status should be 401
$ curl -v --user my_username:password localhost:9200/foo # sends 401

It would be great if you can help address the localhost whitelist issue.

**Comment by skade** [comment]
Wouldn't it be preferable to not bind Elasticsearch to localhost in that case? We will have a look at that though.
