### ISSUE TITLE
Can't get working in ES 1.4.4

### ISSUE THREAD

**Issue by designermonkey** [Asquera/elasticsearch-http-basic#43]
I've installed the latest version with ES 1.4.4, and added a very simple set of credentials to try it out before production use, and in my case, I can still access port 9200 on the server in use.

Any advice?

**Comment by emig** [comment]
@designermonkey localhost is included in the host/ip whitelist by default. You can disable this whitelist setting the value of `http.basic.ipwhitelist` in the configuration to `false`. Is it possible that you are accessing localhost and getting whitelisted?

**Comment by emig** [comment]
closing after no response.
