### ISSUE TITLE
Are both basic auth and whitelist necessary?

### ISSUE THREAD

**Issue by foresightyj** [Asquera/elasticsearch-http-basic#54]
From the README: **A client is authenticated iff its request is trusted and its ip is whitelisted**. It gives me an impression that both basic auth and whitelist are needed for a machine to connect to the ES instance.

However, I only set up username and password and didn't set up the whitelist, yet any machine could connect to my ES instance with the username and the password.

Shouldn't it be **A client is authenticated iff its request is trusted OR its ip is whitelisted**?

**Comment by treehau5** [comment]
If you look at the source, the check for determining whether or not a request is authorized seems to be
````
return allowOptionsForCORS(request) ||
        authBasic(request) || ipAuthorized(request);
````

So yes, it seems to be OR.

Additionally, I can configure `ipwhitelist: false` , and still connect via localhost.

**Comment by emig** [comment]
For the first question, we added ip based authentication to the plugin, and we got an OR.
A client can be authenticated via Basic auth and/or via Ip. But for Ip authentiction this two conditions are needed:
- the request should be *trusted*
- the ip should be whitelisted.

**Comment by emig** [comment]
For the second question, this are the tests with the behaviour expected when the configuration is `ipwhitelist: false`:
https://github.com/Asquera/elasticsearch-http-basic/blob/master/src/test/java/com/asquera/elasticsearch/plugins/http/auth/integration/DisabledWhitelistIntegrationTest.java#L40-L58

be aware that `/` is always authenticated

**Comment by foresightyj** [comment]
Thank you both for the clarifications. Seems I messed up two concepts: basic-auth and ip-based auth. I read the readme again and it is totally clear now.
