### ISSUE TITLE
Java API with http-basic not working

### ISSUE THREAD

**Issue by HemaAnusha** [Asquera/elasticsearch-http-basic#63]
Hello,

Am using Java API for to get response and all the actions in ElasticSearch,

I have downloaded the jar (1.5.1) as am using ES-1.5.2 and kept the jar in plugins/http-basic

And kept the settings as:

http.basic.enabled: true
http.basic.user: es_admin
http.basic.password: es_pwd

Then I restarted the elasticsearch,

In sense plugin for request that has asked username/password..

where as in Java API, without any authentication able to get the response.

Here is My Java Code.

Settings settings = ImmutableSettings.settingsBuilder().put("cluster.name", "elasticsearch").build();
Client client = TransportClient(settings).addTransportAddress(new InetSocketTransportAddress("localhost", 9300));

By using this client am able to search the data..

public static void getResponse(String index, String indextype) throws InvalidFormatException, Exception {
		SearchHits hits = null;
		SearchHit hit = null;
		SearchResponse response = client.prepareSearch(index).setTypes(indextype).execute().actionGet();
		hits = response.getHits();
		Iterator<SearchHit> hitsIte = hits.iterator();
		while (hitsIte.hasNext()) {
			hit = hitsIte.next();
			// jsonArray.add(hit.getSource());
			System.out.println(hit.getSourceAsString());
		}

	}

May I know like how to make the JAVA API to authenticate the host???????????

**Comment by Xylakant** [comment]
Sorry, but this plugin only protects the http/rest api. There are other plugins that can probably do what you want, afaik both search guard and shield can protect the Transport api.

**Comment by HemaAnusha** [comment]
Okay Thank you
