### ISSUE TITLE
How configure multi-users with different rights?

### ISSUE THREAD

**Issue by weiqiangyuan** [Asquera/elasticsearch-http-basic#64]
Hi,

I have installed the http-basic plugins. I have a question as followed:
How to configure multi-users and each user with different rights?

Thank you~

**Comment by emig** [comment]
Hi, 

This plugin provides basic http authentication for a single user.
Authorization functionality is not supported.

The functionality you request is AFAIK provided by [shield](https://www.elastic.co/products/shield)
