### ISSUE TITLE
do you mind if I fork and maintain code base there?

### ISSUE THREAD

**Issue by sweetest** [Asquera/elasticsearch-http-basic#67]
I'm patching this project for 2.3.x version of elasticsearch, already been using that patch for my own cluster.

And I can either push that patch here, or maintain by myself in a different repo. Obviously I prefer the latter for better maintainablity. Before making any action I want to ask for your opinion.

**Comment by Xylakant** [comment]
you're welcome to fork in any case. If you're interested in maintaining the plugin we're also willing to transfer the repo to your account. if you're not interested in maintaining the plugin we'd welcome a PR.
