### ISSUE TITLE
the elasticsearch-http-basic can support es 5.x?

### ISSUE THREAD

**Issue by zqc0512** [Asquera/elasticsearch-http-basic#69]
@skade 
the elasticsearch-http-basic can support es 5.x?
thanks.

**Comment by emig** [comment]
@zqc0512 on the README:

      IMPORTANT NOTICE: This project is currently not supported. We accept pull requests, but  
      we're not doing any feature development/bug fixing

**Comment by lijunwyf21** [comment]
不支持，太悲剧了。摸索了半天

**Comment by zyong812** [comment]
tell me why?

**Comment by Xylakant** [comment]
why what?

**Comment by zyong812** [comment]
why not keep updating and support ES 5.x?

**Comment by Xylakant** [comment]
because it takes time to maintain a plugin and none of the people that built it currently has time to do so.

**Comment by ejunzen** [comment]
oh....no....

**Comment by imjdl** [comment]
Are there good alternatives?

**Comment by skade** [comment]
@imjdl Search Guard has HTTP basic in their community edition: https://docs.search-guard.com/latest/http-basic-authorization

**Comment by imjdl** [comment]
OK, thank you

**Comment by imjdl** [comment]
@skade OK, thank you

**Comment by zyong812** [comment]
use web server (Nginx etc.) in front of ES server
